### ISSUE TITLE
GetPadBuf isn't compilation-unit safe.

### ISSUE THREAD

**Issue by nicolasnoble** [gwald/psyq_to_netyaroze#1]
In the `ny_psyq.h` file, the `GetPadBuf` function tries to declare a local static buffer:

https://github.com/gwald/psyq_to_netyaroze/blob/d649b83a13eb2d64098a4430d3ea37c01c93abda/include/ny_psyq.h#L69-L71

The issue here is that the function itself is declared as `inline`, within a `.h` file. If the function is called from multiple compilation units, then it'll still inline multiple instances of the same function, and each instance will have its own static buffer version, which is probably not what you want here.

I'll send out a proposal for a fix in a minute.

**Comment by gwald** [comment]
Thanks for the fix!
